// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBL6D2FUg_11wF1-mI3BCgd7b5Z6r27l0U',
    appId: '1:694248283781:web:01fe02aa9315d038bf53ec',
    messagingSenderId: '694248283781',
    projectId: 'log-eg',
    authDomain: 'log-eg.firebaseapp.com',
    storageBucket: 'log-eg.appspot.com',
    measurementId: 'G-J3SXBL0Z21',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJdHKS2msLgYWyEpFJbzg0c0n2BUDy8Js',
    appId: '1:694248283781:android:9446e4dfb46e5ba4bf53ec',
    messagingSenderId: '694248283781',
    projectId: 'log-eg',
    storageBucket: 'log-eg.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDp9PA1jFh4zqTpDSFQJ2ImopLmQmvkMpE',
    appId: '1:694248283781:ios:73408a02faa52e03bf53ec',
    messagingSenderId: '694248283781',
    projectId: 'log-eg',
    storageBucket: 'log-eg.appspot.com',
    androidClientId: '694248283781-jlqf2bo8morckn5apsa5koopcuu21397.apps.googleusercontent.com',
    iosClientId: '694248283781-apvfnssvr3h32r04uiiocvn4fsvpnhgs.apps.googleusercontent.com',
    iosBundleId: 'com.example.classico',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDp9PA1jFh4zqTpDSFQJ2ImopLmQmvkMpE',
    appId: '1:694248283781:ios:73408a02faa52e03bf53ec',
    messagingSenderId: '694248283781',
    projectId: 'log-eg',
    storageBucket: 'log-eg.appspot.com',
    androidClientId: '694248283781-jlqf2bo8morckn5apsa5koopcuu21397.apps.googleusercontent.com',
    iosClientId: '694248283781-apvfnssvr3h32r04uiiocvn4fsvpnhgs.apps.googleusercontent.com',
    iosBundleId: 'com.example.classico',
  );
}
